server:
  port: 8083

spring:
  application:
    name: risk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fingaurd
    username: fingaurd
    password: fingaurd123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
