server:
  port: 8081

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fingaurd
    username: fingaurd
    password: fingaurd123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  topics:
    transactions: transactions

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
